//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.30 at 04:31:39 AM EET 
//


package com.service.payment.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.service.payment.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MakePaymentRequest_QNAME = new QName("http://localhost:8080/payment", "makePaymentRequest");
    private final static QName _MakePaymentResponse_QNAME = new QName("http://localhost:8080/payment", "makePaymentResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.service.payment.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MakePaymentRequestType }
     * 
     */
    public MakePaymentRequestType createMakePaymentRequestType() {
        return new MakePaymentRequestType();
    }

    /**
     * Create an instance of {@link MakePaymentResponseType }
     * 
     */
    public MakePaymentResponseType createMakePaymentResponseType() {
        return new MakePaymentResponseType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MakePaymentRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link MakePaymentRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://localhost:8080/payment", name = "makePaymentRequest")
    public JAXBElement<MakePaymentRequestType> createMakePaymentRequest(MakePaymentRequestType value) {
        return new JAXBElement<MakePaymentRequestType>(_MakePaymentRequest_QNAME, MakePaymentRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MakePaymentResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link MakePaymentResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://localhost:8080/payment", name = "makePaymentResponse")
    public JAXBElement<MakePaymentResponseType> createMakePaymentResponse(MakePaymentResponseType value) {
        return new JAXBElement<MakePaymentResponseType>(_MakePaymentResponse_QNAME, MakePaymentResponseType.class, null, value);
    }

}
